plugins = [
    # Installs the plugin from https://github.com/Duckonaut/split-monitor-workspaces
    #"Duckonaut/split-monitor-workspaces",
    # A more explicit definition of the git install
    { git = "https://github.com/VortexCoyote/hyprfocus", branch = "main", name = "hyprfocus" }
    # Installs the same plugin from a local folder
    #{ local = "/home/northerblow/hyprfocus/" },
]
